export const POST_APP_SUGGESTIONS = "POST_APP_SUGGESTIONS";
export const POST_TOP_CHARTS = "POST_TOP_CHARTS";
export const POST_TRACKED_APPS = "POST_TRACKED_APPS";
export const POST_RANK_HISTORY= "POST_RANK_HISTORY";
